<a href="https://colab.research.google.com/github/Huyphung111/TH_DeepLearning/blob/main/Numpy%26pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


my_list = [1, 9, 15, 39]
print("Python list:", my_list)

my_numpy_array = np.array(my_list)
print("Numpy array:", my_numpy_array)

a = np.array([1, 9, 15, 39])
print(a)

Python list: [1, 9, 15, 39]
Numpy array: [ 1  9 15 39]
[ 1  9 15 39]


In [ ]:
import numpy as np

# 1. Array 2 chiều
c = np.array([[1, 2, 3],
              [4, 5, 6]])

print(c)
print(c.shape)
print(c.dtype)


[[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [ ]:
d = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])

print(d)
print(d.shape)



[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [ ]:
# 3. Tạo array toàn 0 và toàn 1
e = np.zeros((2, 2))
f = np.ones((3, 3))

print("Zero matrix:\n", e)
print("One matrix:\n", f)

Zero matrix:
 [[0. 0.]
 [0. 0.]]
One matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
import numpy as np

# ===== 1. Array 2 chiều =====
e = np.array([[1., 2., 3.],
              [4., 5., 6.]])

print("Array e:")
print(e)
print("Shape of e:", e.shape)

# reshape (2x3) -> (3x2)
f = e.reshape(3, 2)
print("Reshape (3,2):")
print(f)


# ===== 2. Array 3 chiều =====
g = np.array([
    [[1., 2., 3.], [4., 5., 6.]],
    [[7., 8., 9.], [10., 11., 12.]]
])

print("\nArray g:")
print(g)
print("Shape of g:", g.shape)

# reshape (2,2,3) -> (3,4)
h = g.reshape(3, 4)
print("Reshape (3,4):")
print(h)

# reshape (2,2,3) -> (3,2,2)
j = g.reshape(3, 2, 2)
print("Reshape (3,2,2):")
print(j)

# reshape (2,2,3) -> (2,3,2)
k = g.reshape(2, 3, 2)
print("Reshape (2,3,2):")
print(k)


# ===== 3. Flatten =====
flat = g.flatten()
print("\nFlatten array:")
print(flat)

Array e:
[[1. 2. 3.]
 [4. 5. 6.]]
Shape of e: (2, 3)
Reshape (3,2):
[[1. 2.]
 [3. 4.]
 [5. 6.]]

Array g:
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
Shape of g: (2, 2, 3)
Reshape (3,4):
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
Reshape (3,2,2):
[[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
Reshape (2,3,2):
[[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]

Flatten array:
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


In [ ]:
e = np.array([[1., 2., 3.],
              [4., 5., 6.]])

f = e.flatten()
print(f)

g = np.array([
    [[1., 2., 3.], [4., 5., 6.]],
    [[7., 8., 9.], [10., 11., 12.]]
])

j = g.flatten()
print(j)

[1. 2. 3. 4. 5. 6.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


In [ ]:
f = np.array([1., 2., 3.])
g = np.array([4., 5., 6.])

h_stack = np.hstack((f, g))
print("Horizontal Append\n", h_stack)

v_stack = np.vstack((f, g))
print("Vertical Append\n", v_stack)

Horizontal Append
 [1. 2. 3. 4. 5. 6.]
Vertical Append
 [[1. 2. 3.]
 [4. 5. 6.]]


In [ ]:
import numpy as np

# Random 1-D array
a = np.random.randint(100, size=(5,))
print("Random 1-D array\n", a)

# Random 2-D array
b = np.random.randint(100, size=(3, 4))
print("Random 2-D array\n", b)

# Random 3-D array
c = np.random.randint(100, size=(3, 4, 3))
print("Random 3-D array\n", c)

Random 1-D array
 [17 78 12 97 73]
Random 2-D array
 [[ 7 64 42 37]
 [ 4 51 32 80]
 [22 74 99 15]]
Random 3-D array
 [[[10 72 75]
  [49 58 60]
  [10 23 59]
  [75 43 60]]

 [[94 29 93]
  [38 46 14]
  [37 30  7]
  [89 98 50]]

 [[58 15 64]
  [41 77 28]
  [84 96  7]
  [10 60 47]]]


In [ ]:
import numpy as np

# ===== 3.7.3 Gaussian (phân phối chuẩn) =====
a = np.random.normal(5, 0.5, 10)
print(a)


# ===== 3.7.4 Random từ mảng cho trước =====

# sinh 1 giá trị ngẫu nhiên
a = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20])
print(a)

# sinh ma trận 3x5 từ mảng giá trị cho trước
b = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20], size=(3, 5))
print(b)

[4.5068361  5.28093996 4.9222415  5.39125129 5.11593522 5.39069411
 4.48667441 5.12763869 4.64152151 5.07558122]
18
[[ 6 20  2 10 10]
 [16 14 14  8 16]
 [ 8 14 10  4  8]]


In [ ]:
# tạo ma trận 5x5 toàn số 1
A = np.matrix(np.ones((5, 5)))
print("The matrix\n", A)

# đổi giá trị dòng thứ 3 (index 2)
np.array(A)[2] = 2
print("Change values of third row with array\n", A)

# đổi lại lần nữa
np.array(A)[2] = 2
print("Change values of third row with asarray\n", A)

The matrix
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with array
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with asarray
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
import numpy as np

# ===== 3.9.1 arange =====

# tạo 20 số từ 1 đến 19
a = np.arange(1, 20)
print(a)

# tạo số từ 1 đến 19, bước nhảy 2
b = np.arange(1, 20, 2)
print(b)


# ===== 3.9.2 linspace =====

# tạo 10 số từ 1 đến 5
c = np.linspace(1, 5, num=10)
print(c)


# ===== 3.10 Index và slice =====

a = np.array([[1, 2, 3],
              [4, 5, 6]])

print(a)

# lấy dòng
print("first row:", a[0])
print("second row:", a[1])

# lấy cột
print("Second column:", a[:, 1])
print("first column:", a[:, 0])

# lấy 2 phần tử đầu của dòng 2
print("First two values of second row:", a[1, :2])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]
[[1 2 3]
 [4 5 6]]
first row: [1 2 3]
second row: [4 5 6]
Second column: [2 5]
first column: [1 4]
First two values of second row: [4 5]


In [ ]:
#2 import numpy as np
import pandas as pd

# ===== 1. NumPy → Pandas =====
h = np.array([[1, 2],
              [3, 4]])

df_h = pd.DataFrame(h)
print("DataFrame:\n", df_h)


# ===== 2. Pandas → NumPy =====
numpy_h = np.array(df_h)
print("Numpy array:\n", numpy_h)


# ===== 3. Tạo DataFrame từ dictionary =====
dic = {
    'Name': ['John', 'Smith'],
    'Age': [30, 40]
}

df_dic = pd.DataFrame(dic)
print(df_dic)


# ===== 4. Tạo DataFrame 20x4 ngẫu nhiên =====
r = np.random.randn(20, 4)

df = pd.DataFrame(r, columns=['so1', 'so2', 'so3', 'so4'])

# in 5 dòng đầu
print(df.head())

DataFrame:
    0  1
0  1  2
1  3  4
Numpy array:
 [[1 2]
 [3 4]]
    Name  Age
0   John   30
1  Smith   40
        so1       so2       so3       so4
0  1.388809 -0.730523  0.228481 -0.648361
1 -1.173187  0.228937 -0.747103  0.341099
2  0.731341 -0.679792 -1.055320  1.129387
3 -0.358840 -0.025414 -0.209935  0.334616
4 -0.685108  0.791925 -1.207892  0.750219


In [ ]:
import numpy as np
import pandas as pd

# ===== tạo mảng 20 x 4 =====
r = np.random.randn(20, 4)

df = pd.DataFrame(r, columns=['so1', 'so2', 'so3', 'so4'])

# in 5 dòng đầu
print(df.head())

# ===== chọn 1 cột =====
print("Chọn cột so1\n", df['so1'])

# ===== chọn nhiều dòng =====
print("Chọn nhiều dòng\n", df[0:3])

# ===== chọn nhiều cột =====
print("Chọn nhiều cột\n", df[['so1', 'so3']])

# ===== chọn nhiều dòng, nhiều cột =====
print("Chọn nhiều dòng, nhiều cột\n", df.iloc[:3, :2])

# ===== xóa cột =====
df = df.drop(columns=['so1', 'so4'])

print(df)

        so1       so2       so3       so4
0  0.446918 -1.068829  0.005540  1.244801
1 -0.584487  2.225239  0.227510 -0.406860
2  0.556752  0.394994 -0.797046  0.854307
3  0.422492 -0.276256 -1.463048 -0.175243
4  0.118597  0.634745  0.288621 -0.236845
Chọn cột so1
 0     0.446918
1    -0.584487
2     0.556752
3     0.422492
4     0.118597
5    -1.936858
6     0.120301
7     1.384413
8     2.060955
9    -0.479176
10    0.735636
11    0.957857
12    0.057133
13   -0.296413
14    2.651170
15    0.018875
16   -0.142920
17    0.109997
18    0.090103
19   -1.382736
Name: so1, dtype: float64
Chọn nhiều dòng
         so1       so2       so3       so4
0  0.446918 -1.068829  0.005540  1.244801
1 -0.584487  2.225239  0.227510 -0.406860
2  0.556752  0.394994 -0.797046  0.854307
Chọn nhiều cột
          so1       so3
0   0.446918  0.005540
1  -0.584487  0.227510
2   0.556752 -0.797046
3   0.422492 -1.463048
4   0.118597  0.288621
5  -1.936858  1.055172
6   0.120301 -0.173576
7   1.384413 -0.533454


In [ ]:
import pandas as pd

# ===== tạo 2 DataFrame =====
df1 = pd.DataFrame({
    'Name': ['John', 'Smith', 'Paul'],
    'Age': [25, 30, 50]
}, index=[0, 1, 2])

df2 = pd.DataFrame({
    'Name': ['Adam', 'Smith'],
    'Age': [26, 11]
}, index=[3, 4])


# ===== nối 2 DataFrame =====
df_concat = pd.concat([df1, df2])
print("Concate two DataFrame\n", df_concat)


# ===== xóa giá trị trùng =====
print("Drop duplicate values in DataFrame\n",
      df_concat.drop_duplicates('Name'))


# ===== sắp xếp theo cột Age =====
print("Sort values in DataFrame\n",
      df_concat.sort_values('Age'))


# ===== đổi tên cột =====
df_rename = df_concat.rename(columns={
    'Name': 'Surname',
    'Age': 'Age_pupil'
})

print("Rename columns of DataFrame\n", df_rename)

Concate two DataFrame
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
4  Smith   11
Drop duplicate values in DataFrame
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
Sort values in DataFrame
     Name  Age
4  Smith   11
0   John   25
3   Adam   26
1  Smith   30
2   Paul   50
Rename columns of DataFrame
   Surname  Age_pupil
0    John         25
1   Smith         30
2    Paul         50
3    Adam         26
4   Smith         11


In [ ]:
import pandas as pd

# ===== Đọc dữ liệu từ CSV =====

path = "salary_data.csv"

COLUMNS = ['YearsExperience', 'Salary']

# cách 1: tự đặt tên cột
df_csv = pd.read_csv(path,
                     skipinitialspace=True,
                     names=COLUMNS,
                     index_col=False)

print(df_csv.head())
print(df_csv.shape)


# cách 2: dùng header có sẵn trong file
df_csv1 = pd.read_csv(path,
                      skipinitialspace=True,
                      index_col=False)

print(df_csv1.head())
print(df_csv1.shape)

   YearsExperience    Salary
0  YearsExperience    Salary
1              1.1  39343.00
2              1.3  46205.00
3              1.5  37731.00
4              2.0  43525.00
(31, 2)
   YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0
(30, 2)


In [ ]:
import pandas as pd

# ===== Đọc dữ liệu =====
path = "Fish.csv"   # nhớ đặt file đúng tên và cùng thư mục

df_csv = pd.read_csv(path,
                     skipinitialspace=True,
                     index_col=False)

# ===== in dữ liệu =====
print(df_csv.head())


# ===== nhóm theo Species và tính trung bình =====
print(df_csv.groupby(['Species']).mean().head())


# ===== nhóm theo Species, lấy min của Weight =====
print(df_csv.groupby(['Species'])['Weight'].min().head())


# ===== nhóm theo Species + Height, lấy min Weight =====
print(df_csv.groupby(['Species', 'Height'])['Weight'].min().head())

  Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340
             Weight    Length1    Length2    Length3     Height     Width
Species                                                                  
Bream    617.828571  30.305714  33.108571  38.354286  15.183211  5.427614
Parkki   154.818182  18.727273  20.345455  22.790909   8.962427  3.220736
Perch    382.239286  25.735714  27.892857  29.571429   7.861870  4.745723
Pike     718.705882  42.476471  45.482353  48.717647   7.713771  5.086382
Roach    152.050000  20.645000  22.275000  24.970000   6.694795  3.657850
Species
Bream     242.0
Parkki     55.0
Perch       5.9
Pike      200.0
Roach       0.0
Name: Weight, dtype: f