<a href="https://colab.research.google.com/github/Huyphung111/TH_DeepLearning/blob/main/TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

# Tensor 0-chiều (scalar)
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

r1 = tf.constant(9, tf.int16)
print(r1)

r1_float = tf.constant(1.12, tf.float32)
print(r1_float)

r1_string = tf.constant('Hello Vanlang University', tf.string)
print(r1_string)


# Tensor 1-chiều (vector)
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)


# Tensor 2-chiều (ma trận)
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
print(rank_2_tensor)


# Tensor 3-chiều
rank_3_tensor = tf.constant([
    [[0, 1, 2, 3, 4],
     [5, 6, 7, 8, 9]],

    [[10, 11, 12, 13, 14],
     [15, 16, 17, 18, 19]],

    [[20, 21, 22, 23, 24],
     [25, 26, 27, 28, 29]]
])
print(rank_3_tensor)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int16)
tf.Tensor(1.12, shape=(), dtype=float32)
tf.Tensor(b'Hello Vanlang University', shape=(), dtype=string)
tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)
tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)
tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [2]:
# Tensor 3-chiều + shape + dtype
rank_3_tensor = tf.constant([
    [[0, 1, 2, 3, 4],
     [5, 6, 7, 8, 9]],

    [[10, 11, 12, 13, 14],
     [15, 16, 17, 18, 19]],

    [[20, 21, 22, 23, 24],
     [25, 26, 27, 28, 29]]
])

print(rank_3_tensor)
print("shape:", rank_3_tensor.shape)
print("type of tensor:", rank_3_tensor.dtype)


# Tensor toàn số 0
t_zero = tf.zeros(10)
print(t_zero)

t_2_zero = tf.zeros([3, 3])
print(t_2_zero)

t_3_zero = tf.zeros([3, 3, 5])
print(t_3_zero)


# Tensor toàn số 1
t_one = tf.ones(10)
print(t_one)

t_2_one = tf.ones([3, 3])
print(t_2_one)

t_3_one = tf.ones([3, 3, 5])
print(t_3_one)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)
shape: (3, 2, 5)
type of tensor: <dtype: 'int32'>
tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 3, 5), dtype=float32)
tf.Tensor([1. 1. 1. 1. 1. 1. 1. 1. 1. 1.], shape=(10,), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]], shape=(3, 3, 5), dtype=float32)


In [3]:
# tf.fill
t_1 = tf.fill([3], 10)
print(t_1)

t_2 = tf.fill([3, 3], 9)
print(t_2)


# linspace
lin_tensor = tf.linspace(5.0, 20.0, 5)
print(lin_tensor)


# range
range_tensor = tf.range(3.0, 7.0, delta=0.5)
print(range_tensor)

range_tensor2 = tf.range(3.0, delta=0.5)
print(range_tensor2)


# random normal
rand_normal_1 = tf.random.normal([5])
print(rand_normal_1)

rand_normal_2 = tf.random.normal([3, 3])
print(rand_normal_2)


# truncated normal
rand_trunc_1 = tf.random.truncated_normal([5])
print(rand_trunc_1)

rand_trunc_2 = tf.random.truncated_normal([3, 2])
print(rand_trunc_2)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor(
[[9 9 9]
 [9 9 9]
 [9 9 9]], shape=(3, 3), dtype=int32)
tf.Tensor([ 5.    8.75 12.5  16.25 20.  ], shape=(5,), dtype=float32)
tf.Tensor([3.  3.5 4.  4.5 5.  5.5 6.  6.5], shape=(8,), dtype=float32)
tf.Tensor([0.  0.5 1.  1.5 2.  2.5], shape=(6,), dtype=float32)
tf.Tensor([ 1.1320894  -0.41597703 -1.2207805  -0.6553344   0.17376427], shape=(5,), dtype=float32)
tf.Tensor(
[[-0.7886581   0.08937158 -0.0092567 ]
 [-1.5586486   0.12514494  1.9936988 ]
 [-0.34839472 -0.12766328  0.23979191]], shape=(3, 3), dtype=float32)
tf.Tensor([ 0.14896987 -0.46119493 -0.33420226  0.97185415  0.14880559], shape=(5,), dtype=float32)
tf.Tensor(
[[-0.5231281  -1.0427773 ]
 [ 0.58394283 -0.06663913]
 [-0.1257242   0.58453065]], shape=(3, 2), dtype=float32)


In [4]:
# Chuyển kiểu dữ liệu
t_float = tf.constant(3.9, tf.float32)
print(t_float, "---", t_float.dtype)

t_int = tf.cast(t_float, dtype=tf.int32)
print(t_int, "---", t_int.dtype)


# Căn bậc 2
x = tf.constant(2, dtype=tf.float32)
print(tf.sqrt(x))


# Cộng 2 tensor
a = tf.constant([[1, 2]], tf.int32)
b = tf.constant([[3, 4]], tf.int32)

c = tf.add(a, b)
d = a + b

print(c)
print(d)


# Nhân 2 tensor
a = tf.constant([[1, 2]], tf.int32)
b = tf.constant([[3, 4]], tf.int32)

c = tf.multiply(a, b)
d = a * b

print(c)
print(d)


# Các phép toán khác
a = tf.constant([6., 6., 6.])
b = tf.constant([4., 4., 4.])
c = tf.constant([3., 3., 3.])

d = tf.add(a, b)
e = tf.add_n([a, b, c])
f = tf.subtract(a, b)
g = tf.multiply(a, b)
h = tf.divide(a, b)
i = tf.scalar_mul(3, a)
j = tf.math.reciprocal(a)
k = tf.math.mod(a, b)
l = tf.negative(a)

print(f)
print(l)

tf.Tensor(3.9, shape=(), dtype=float32) --- <dtype: 'float32'>
tf.Tensor(3, shape=(), dtype=int32) --- <dtype: 'int32'>
tf.Tensor(1.4142135, shape=(), dtype=float32)
tf.Tensor([[4 6]], shape=(1, 2), dtype=int32)
tf.Tensor([[4 6]], shape=(1, 2), dtype=int32)
tf.Tensor([[3 8]], shape=(1, 2), dtype=int32)
tf.Tensor([[3 8]], shape=(1, 2), dtype=int32)
tf.Tensor([2. 2. 2.], shape=(3,), dtype=float32)
tf.Tensor([-6. -6. -6.], shape=(3,), dtype=float32)


In [5]:
t = tf.constant([-6.5, -3.5, 3.5, 6.5])

r1 = tf.round(t)
r2 = tf.math.rint(t)
r3 = tf.math.ceil(t)
r4 = tf.math.floor(t)

print(r4)

tf.Tensor([-7. -4.  3.  6.], shape=(4,), dtype=float32)


In [6]:
t1 = tf.constant([4., 3., 2.])
t2 = tf.constant([3., 2., 1.])
t3 = tf.constant([[1, 2, 3],
                  [4, 5, 6]])
t4 = tf.constant([[7, 8],
                  [9, 10],
                  [11, 12]])

dot_x = tf.tensordot(t1, t2, 0)
dot_y = tf.tensordot(t1, t2, 1)

print(t1)
print(t2)
print(t3)
print(t4)

cross = tf.linalg.cross(t1, t2)
mm = tf.matmul(t3, t4)
d = tf.linalg.diag(t1)
trace = tf.linalg.trace(t3)
trans = tf.transpose(t3)
eye = tf.eye(5)

print(dot_x)
print(d)
print(cross)
print(trace)
print(trans)
print(eye)

tf.Tensor([4. 3. 2.], shape=(3,), dtype=float32)
tf.Tensor([3. 2. 1.], shape=(3,), dtype=float32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[12.  8.  4.]
 [ 9.  6.  3.]
 [ 6.  4.  2.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[4. 0. 0.]
 [0. 3. 0.]
 [0. 0. 2.]], shape=(3, 3), dtype=float32)
tf.Tensor([-1.  2. -1.], shape=(3,), dtype=float32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]], shape=(5, 5), dtype=float32)


In [7]:
# Variable
toan = tf.Variable(8.5, dtype=tf.float32)
print(toan)

diem = tf.Variable([5, 9])
print(diem)

print("Shape:", diem.shape)
print("Dtype:", diem.dtype)
print("numpy:", diem.numpy())


# Gán giá trị
toan = tf.Variable(8.5, dtype=tf.float32)
print(toan)

diem = tf.Variable([5, 9])
print(diem)

diem.assign([8, 10])
print(diem)


# assign_add, assign_sub
toan = tf.Variable(8.5, dtype=tf.float32)
print(toan)

diem = tf.Variable([5, 9])
print(diem)

diem.assign([8, 10])
diem.assign_add([1, 1])
print(diem)

diem.assign_sub([5, 5])
print(diem)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=8.5>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 9], dtype=int32)>
Shape: (2,)
Dtype: <dtype: 'int32'>
numpy: [5 9]
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=8.5>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 9], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 8, 10], dtype=int32)>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=8.5>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 9], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 9, 11], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([4, 6], dtype=int32)>


In [8]:
# Function thường
def a_regular_function(x, y, b):
    x = tf.matmul(x, y)
    x = x + b
    return x

# Chuyển sang graph
a_function_that_uses_a_graph = tf.function(a_regular_function)

# Tạo dữ liệu
x1 = tf.constant([[1.0, 2.0]])
y1 = tf.constant([[2.0], [3.0]])
b1 = tf.constant(4.0)

# Gọi hàm
orig_value = a_regular_function(x1, y1, b1).numpy()
tf_function_value = a_function_that_uses_a_graph(x1, y1, b1).numpy()

print(orig_value)
print(tf_function_value)

[[12.]]
[[12.]]


In [9]:
def inner_function(x, y, b):
    x = tf.matmul(x, y)
    x = x + b
    return x

@tf.function
def outer_function(x):
    y = tf.constant([[2.0], [3.0]])
    b = tf.constant(4.0)
    return inner_function(x, y, b)

rs = outer_function(tf.constant([[1.0, 2.0]])).numpy()
print(rs)

[[12.]]


In [10]:
class SimpleModule(tf.Module):
    def __init__(self, name=None):
        super().__init__(name=name)
        self.a_variable = tf.Variable(5.0, name="train_me")
        self.non_trainable_variable = tf.Variable(5.0, trainable=False, name="do_not_train_me")

    def __call__(self, x):
        return self.a_variable * x + self.non_trainable_variable


simple_module = SimpleModule(name="simple")

rs = simple_module(tf.constant(5.0))
print(rs)

print("Train variables:", simple_module.trainable_variables)
print("All variables:", simple_module.variables)

tf.Tensor(30.0, shape=(), dtype=float32)
Train variables: (<tf.Variable 'train_me:0' shape=() dtype=float32, numpy=5.0>,)
All variables: (<tf.Variable 'train_me:0' shape=() dtype=float32, numpy=5.0>, <tf.Variable 'do_not_train_me:0' shape=() dtype=float32, numpy=5.0>)


In [11]:
class Dense(tf.Module):
    def __init__(self, in_features, out_features, name=None):
        super().__init__(name=name)
        self.w = tf.Variable(
            tf.random.normal([in_features, out_features]), name="w"
        )
        self.b = tf.Variable(tf.zeros([out_features]), name="b")

    def __call__(self, x):
        y = tf.matmul(x, self.w) + self.b
        return tf.nn.relu(y)


class SequentialModule(tf.Module):
    def __init__(self, name=None):
        super().__init__(name=name)
        self.dense_1 = Dense(in_features=3, out_features=3)
        self.dense_2 = Dense(in_features=3, out_features=2)

    def __call__(self, x):
        x = self.dense_1(x)
        return self.dense_2(x)


my_model = SequentialModule(name="the_model")

print("Model results:", my_model(tf.constant([[2.0, 2.0, 2.0]])))

Model results: tf.Tensor([[8.244631 0.      ]], shape=(1, 2), dtype=float32)
